// components/pagination/MiniSelect.jsx
import VcSelect, { SelectProps } from '../select';
import { getOptionProps, filterEmpty } from '../_util/props-util';

export default {
  props: {
    ...SelectProps,
  },
  Option: VcSelect.Option,
  render() {
    const selectOptionsProps = getOptionProps(this);
    const selelctProps = {
      props: {
        ...selectOptionsProps,
        size: 'small',
      },
      on: this.$listeners,
    };
    return <VcSelect {...selelctProps}>{filterEmpty(this.$slots.default)}</VcSelect>;
  },
};

// components/pagination/MiniSelect.vue
<script>
import VcSelect, { SelectProps } from '../select'
import { getOptionProps, filterEmpty } from '../_util/props-util'

export default {
  props: {
    ...SelectProps,
  },
  Option: VcSelect.Option,
  render () {
    const selectOptionsProps = getOptionProps(this)
    const selelctProps = {
      props: {
        ...selectOptionsProps,
        size: 'small',
      },
      on: this.$listeners,
    }
    return <VcSelect {...selelctProps}>{filterEmpty(this.$slots.default)}</VcSelect>
  },
}
</script>
