// components/vc-switch/demo/simple.vue
<script>
import VcSwitch from '../index'
import '../assets/index.less'

export default {
  data () {
    return {
      disabled: false,
    }
  },
  methods: {
    toggle () {
      this.disabled = !this.disabled
    },
    onChange (value) {
      console.log(`switch checked: ${value}`); // eslint-disable-line
    },
  },
  render () {
    return (
      <div style='margin: 20px'>
        <VcSwitch
          onChange={this.onChange}
          disabled={this.disabled}
          checkedChildren={'开'}
          unCheckedChildren={'关'}
        />
        <div style='margin-top: 20px'>
          <button onClick={this.toggle}>toggle disabled</button>
        </div>
      </div>
    )
  },
}
</script>

// components/vc-dropdown/demo/simple.jsx
import Menu, { Item as MenuItem, Divider } from '../../vc-menu/index';
import Dropdown from '../src/index.js';
import '../assets/index.less';

export default {
  data() {
    return {};
  },
  methods: {
    onSelect({ key }) {
      console.log(`${key} selected`);
    },
    onVisibleChange(visible) {
      console.log(visible);
    },
  },
  render() {
    return (
      <div style="margin: 100px">
        <div style="height: 100px"/>
        <div>
          <Dropdown
            trigger={['click']}
            animation="slide-up"
            onVisibleChange={this.onVisibleChange}
          >
            <Menu slot="overlay" onSelect={this.onSelect}>
              <MenuItem disabled>disabled</MenuItem>
              <MenuItem key="1">one</MenuItem>
              <Divider />
              <MenuItem key="2">two</MenuItem>
            </Menu>
            <button style="width: 100px">open</button>
          </Dropdown>
        </div>
      </div>
    );
  },
};
