// components/vc-dialog/LazyRenderBox.jsx
import PropTypes from '../_util/vue-types';
import { getListeners } from '../_util/props-util';

const ILazyRenderBoxPropTypes = {
  visible: PropTypes.bool,
  hiddenClassName: PropTypes.string,
  forceRender: PropTypes.bool,
};

export default {
  props: ILazyRenderBoxPropTypes,
  render() {
    return <div {...{ on: getListeners(this) }}>{this.$slots.default}</div>;
  },
};

// components/vc-dialog/LazyRenderBox.vue
<script>
import PropTypes from '../_util/vue-types'

const ILazyRenderBoxPropTypes = {
  visible: PropTypes.bool,
  hiddenClassName: PropTypes.string,
}

export default {
  props: ILazyRenderBoxPropTypes,
  render () {
    return (
      <div>
        {this.$slots.default}
      </div>
    )
  },
}

</script>
