// site/src/components/antdv-token-previewer/component-demos/tag/info.tsx
import { Tag } from 'ant-design-vue';
import type { ComponentDemo } from '../../interface';

const Demo = () => <Tag color="processing">Info</Tag>;

const componentDemo: ComponentDemo = {
  demo: <Demo />,
  tokens: ['colorInfo', 'colorInfoBg', 'colorInfoBorder'],
  key: 'info',
};

export default componentDemo;

// site/src/components/antdv-token-previewer/component-demos/message/info.tsx
import { defineComponent } from 'vue';
import { message } from 'ant-design-vue';
import type { ComponentDemo } from '../../interface';

const { _InternalPanelDoNotUseOrYouWillBeFired } = message;

const Demo = defineComponent({
  setup() {
    return () => <_InternalPanelDoNotUseOrYouWillBeFired type={'info'} content={'Info'} />;
  },
});

const componentDemo: ComponentDemo = {
  demo: <Demo />,
  tokens: ['colorInfo'],
  key: 'info',
};

export default componentDemo;
