// site/src/components/antdv-token-previewer/component-demos/modal/info.tsx
import { Modal } from 'ant-design-vue';
import type { ComponentDemo } from '../../interface';

const { _InternalPanelDoNotUseOrYouWillBeFired } = Modal;
const Demo = () => {
  return (
    <>
      <_InternalPanelDoNotUseOrYouWillBeFired title="Basic Modal">
        <p>Some contents...</p> <p>Some contents...</p> <p>Some contents...</p>
      </_InternalPanelDoNotUseOrYouWillBeFired>
    </>
  );
};

const componentDemo: ComponentDemo = {
  demo: <Demo />,
  tokens: ['colorInfo'],
  key: 'info',
};
export default componentDemo;

// site/src/components/antdv-token-previewer/component-demos/notification/info.tsx
import { defineComponent } from 'vue';
import { notification } from 'ant-design-vue';
import type { ComponentDemo } from '../../interface';

const { _InternalPanelDoNotUseOrYouWillBeFired } = notification;

const Demo = defineComponent({
  setup() {
    return () => (
      <_InternalPanelDoNotUseOrYouWillBeFired
        message={'Notification Title'}
        type={'info'}
        description={
          'This is the content of the notification. This is the content of the notification. This is the content of the notification.'
        }
      />
    );
  },
});

const componentDemo: ComponentDemo = {
  demo: <Demo />,
  tokens: ['colorInfo'],
  key: 'info',
};

export default componentDemo;
