// components/vc-menu/Menu.vue
<script>
import PropTypes from '../_util/vue-types'
import MenuMixin from './MenuMixin'
import BaseMixin from '../_util/BaseMixin'
import hasProp from '../_util/props-util'
import commonPropsType from './commonPropsType'

const Menu = {
  name: 'Menu',
  props: {
    ...commonPropsType,
    selectable: PropTypes.bool.def(true),
  },
  mixins: [BaseMixin, MenuMixin],

  data () {
    const props = this.$props
    let sSelectedKeys = props.defaultSelectedKeys
    let sOpenKeys = props.defaultOpenKeys
    if (hasProp(this, 'selectedKeys')) {
      sSelectedKeys = props.selectedKeys || []
    }
    if (hasProp(this, 'openKeys')) {
      sOpenKeys = props.openKeys || []
    }

    // this.isRootMenu = true
    return {
      sSelectedKeys,
      sOpenKeys,
    }
  },
  watch: {
    '$props': {
      handler: function (nextProps) {
        if (hasProp(this, 'selectedKeys')) {
          this.setState({
            sSelectedKeys: nextProps.selectedKeys || [],
          })
        }
        if (hasProp(this, 'openKeys')) {
          this.setState({
            sOpenKeys: nextProps.openKeys || [],
          })
        }
      },
      deep: true,
    },
  },
  methods: {
    // onDestroy (key) {
    //   const state = this.$data
    //   const sSelectedKeys = state.sSelectedKeys
    //   const sOpenKeys = state.sOpenKeys
    //   let index = sSelectedKeys.indexOf(key)
    //   if (!hasProp(this, 'selectedKeys') && index !== -1) {
    //     sSelectedKeys.splice(index, 1)
    //   }
    //   index = sOpenKeys.indexOf(key)
    //   if (!hasProp(this, 'openKeys') && index !== -1) {
    //     sOpenKeys.splice(index, 1)
    //   }
    // },

    onSelect (selectInfo) {
      const props = this.$props
      if (props.selectable) {
      // root menu
        let sSelectedKeys = this.$data.sSelectedKeys
        const selectedKey = selectInfo.key
        if (props.multiple) {
          sSelectedKeys = sSelectedKeys.concat([selectedKey])
        } else {
          sSelectedKeys = [selectedKey]
        }
        if (!hasProp(this, 'selectedKeys')) {
          this.setState({
            sSelectedKeys,
          })
        }
        this.__emit('select', {
          ...selectInfo,
          selectedKeys: sSelectedKeys,
        })
      }
    },

    onClick (e) {
      this.__emit('click', e)
    },

    onOpenChange (event) {
      const sOpenKeys = this.$data.sOpenKeys.concat()
      let changed = false
      const processSingle = (e) => {
        let oneChanged = false
        if (e.open) {
          oneChanged = sOpenKeys.indexOf(e.key) === -1
          if (oneChanged) {
            sOpenKeys.push(e.key)
          }
        } else {
          const index = sOpenKeys.indexOf(e.key)
          oneChanged = index !== -1
          if (oneChanged) {
            sOpenKeys.splice(index, 1)
          }
        }
        changed = changed || oneChanged
      }
      if (Array.isArray(event)) {
      // batch change call
        event.forEach(processSingle)
      } else {
        processSingle(event)
      }
      if (changed) {
        if (!hasProp(this, 'openKeys')) {
          this.setState({ sOpenKeys })
        }
        this.__emit('openChange', sOpenKeys)
      }
    },

    onDeselect (selectInfo) {
      const props = this.$props
      if (props.selectable) {
        const sSelectedKeys = this.$data.sSelectedKeys.concat()
        const selectedKey = selectInfo.key
        const index = sSelectedKeys.indexOf(selectedKey)
        if (index !== -1) {
          sSelectedKeys.splice(index, 1)
        }
        if (!hasProp(this, 'selectedKeys')) {
          this.setState({
            sSelectedKeys,
          })
        }
        this.__emit('deselect', {
          ...selectInfo,
          selectedKeys: sSelectedKeys,
        })
      }
    },

    getOpenTransitionName () {
      const props = this.$props
      let transitionName = props.openTransitionName
      const animationName = props.openAnimation
      if (!transitionName && typeof animationName === 'string') {
        transitionName = `${props.prefixCls}-open-${animationName}`
      }
      return transitionName
    },

    isInlineMode () {
      return this.$props.mode === 'inline'
    },

    lastOpenSubMenu () {
      let lastOpen = []
      const { sOpenKeys } = this.$data
      if (sOpenKeys.length) {
        lastOpen = this.getFlatInstanceArray().filter((c) => {
          return c && sOpenKeys.indexOf(c.eventKey) !== -1
        })
      }
      return lastOpen[0]
    },

    renderMenuItem (c, i, subIndex) {
      if (!c) {
        return null
      }
      const state = this.$data
      const extraProps = {
        openKeys: state.sOpenKeys,
        selectedKeys: state.sSelectedKeys,
        triggerSubMenuAction: this.$props.triggerSubMenuAction,
        isRootMenu: this.isRootMenu,
      }
      return this.renderCommonMenuItem(c, i, subIndex, extraProps)
    },
  },

  render () {
    const props = { ...this.$props }
    props.class = ` ${props.prefixCls}-root`
    return this.renderRoot(props, this.$slots.default)
  },
}
export default Menu
</script>

// components/menu/src/Menu.jsx
// import React from 'react';
import PropTypes from 'prop-types'
import createReactClass from 'create-react-class'
import MenuMixin from './MenuMixin'
import { noop } from './util'

const Menu = createReactClass({
  displayName: 'Menu',

  propTypes: {
    defaultSelectedKeys: PropTypes.arrayOf(PropTypes.string),
    selectedKeys: PropTypes.arrayOf(PropTypes.string),
    defaultOpenKeys: PropTypes.arrayOf(PropTypes.string),
    openKeys: PropTypes.arrayOf(PropTypes.string),
    mode: PropTypes.oneOf(['horizontal', 'vertical', 'vertical-left', 'vertical-right', 'inline']),
    getPopupContainer: PropTypes.func,
    onClick: PropTypes.func,
    onSelect: PropTypes.func,
    onDeselect: PropTypes.func,
    onDestroy: PropTypes.func,
    openTransitionName: PropTypes.string,
    openAnimation: PropTypes.oneOfType([PropTypes.string, PropTypes.object]),
    subMenuOpenDelay: PropTypes.number,
    subMenuCloseDelay: PropTypes.number,
    forceSubMenuRender: PropTypes.bool,
    triggerSubMenuAction: PropTypes.string,
    level: PropTypes.number,
    selectable: PropTypes.bool,
    multiple: PropTypes.bool,
    children: PropTypes.any,
  },

  mixins: [MenuMixin],

  isRootMenu: true,

  getDefaultProps () {
    return {
      selectable: true,
      onClick: noop,
      onSelect: noop,
      onOpenChange: noop,
      onDeselect: noop,
      defaultSelectedKeys: [],
      defaultOpenKeys: [],
      subMenuOpenDelay: 0,
      subMenuCloseDelay: 0.1,
      triggerSubMenuAction: 'hover',
    }
  },

  getInitialState () {
    const props = this.props
    let selectedKeys = props.defaultSelectedKeys
    let openKeys = props.defaultOpenKeys
    if ('selectedKeys' in props) {
      selectedKeys = props.selectedKeys || []
    }
    if ('openKeys' in props) {
      openKeys = props.openKeys || []
    }
    return {
      selectedKeys,
      openKeys,
    }
  },

  componentWillReceiveProps (nextProps) {
    const props = {}
    if ('selectedKeys' in nextProps) {
      props.selectedKeys = nextProps.selectedKeys || []
    }
    if ('openKeys' in nextProps) {
      props.openKeys = nextProps.openKeys || []
    }
    this.setState(props)
  },

  onDestroy (key) {
    const state = this.state
    const props = this.props
    const selectedKeys = state.selectedKeys
    const openKeys = state.openKeys
    let index = selectedKeys.indexOf(key)
    if (!('selectedKeys' in props) && index !== -1) {
      selectedKeys.splice(index, 1)
    }
    index = openKeys.indexOf(key)
    if (!('openKeys' in props) && index !== -1) {
      openKeys.splice(index, 1)
    }
  },

  onSelect (selectInfo) {
    const props = this.props
    if (props.selectable) {
      // root menu
      let selectedKeys = this.state.selectedKeys
      const selectedKey = selectInfo.key
      if (props.multiple) {
        selectedKeys = selectedKeys.concat([selectedKey])
      } else {
        selectedKeys = [selectedKey]
      }
      if (!('selectedKeys' in props)) {
        this.setState({
          selectedKeys,
        })
      }
      props.onSelect({
        ...selectInfo,
        selectedKeys,
      })
    }
  },

  onClick (e) {
    this.props.onClick(e)
  },

  onOpenChange (e_) {
    const props = this.props
    const openKeys = this.state.openKeys.concat()
    let changed = false
    const processSingle = (e) => {
      let oneChanged = false
      if (e.open) {
        oneChanged = openKeys.indexOf(e.key) === -1
        if (oneChanged) {
          openKeys.push(e.key)
        }
      } else {
        const index = openKeys.indexOf(e.key)
        oneChanged = index !== -1
        if (oneChanged) {
          openKeys.splice(index, 1)
        }
      }
      changed = changed || oneChanged
    }
    if (Array.isArray(e_)) {
      // batch change call
      e_.forEach(processSingle)
    } else {
      processSingle(e_)
    }
    if (changed) {
      if (!('openKeys' in this.props)) {
        this.setState({ openKeys })
      }
      props.onOpenChange(openKeys)
    }
  },

  onDeselect (selectInfo) {
    const props = this.props
    if (props.selectable) {
      const selectedKeys = this.state.selectedKeys.concat()
      const selectedKey = selectInfo.key
      const index = selectedKeys.indexOf(selectedKey)
      if (index !== -1) {
        selectedKeys.splice(index, 1)
      }
      if (!('selectedKeys' in props)) {
        this.setState({
          selectedKeys,
        })
      }
      props.onDeselect({
        ...selectInfo,
        selectedKeys,
      })
    }
  },

  getOpenTransitionName () {
    const props = this.props
    let transitionName = props.openTransitionName
    const animationName = props.openAnimation
    if (!transitionName && typeof animationName === 'string') {
      transitionName = `${props.prefixCls}-open-${animationName}`
    }
    return transitionName
  },

  isInlineMode () {
    return this.props.mode === 'inline'
  },

  lastOpenSubMenu () {
    let lastOpen = []
    const { openKeys } = this.state
    if (openKeys.length) {
      lastOpen = this.getFlatInstanceArray().filter((c) => {
        return c && openKeys.indexOf(c.props.eventKey) !== -1
      })
    }
    return lastOpen[0]
  },

  renderMenuItem (c, i, subIndex) {
    if (!c) {
      return null
    }
    const state = this.state
    const extraProps = {
      openKeys: state.openKeys,
      selectedKeys: state.selectedKeys,
      triggerSubMenuAction: this.props.triggerSubMenuAction,
    }
    return this.renderCommonMenuItem(c, i, subIndex, extraProps)
  },

  render () {
    const props = { ...this.props }
    props.className += ` ${props.prefixCls}-root`
    return this.renderRoot(props)
  },
})

export default Menu
