// site/src/components/antdv-token-previewer/component-demos/notification/success.tsx
import { defineComponent } from 'vue';
import { notification } from 'ant-design-vue';
import type { ComponentDemo } from '../../interface';

const { _InternalPanelDoNotUseOrYouWillBeFired } = notification;

const Demo = defineComponent({
  setup() {
    return () => (
      <_InternalPanelDoNotUseOrYouWillBeFired
        message={'Notification Title'}
        type={'success'}
        description={
          'This is the content of the notification. This is the content of the notification. This is the content of the notification.'
        }
      />
    );
  },
});

const componentDemo: ComponentDemo = {
  demo: <Demo />,
  tokens: ['colorSuccess'],
  key: 'success',
};

export default componentDemo;

// site/src/components/antdv-token-previewer/component-demos/modal/success.tsx
import { Modal } from 'ant-design-vue';

import type { ComponentDemo } from '../../interface';

const Demo = () => {
  return (
    <Modal._InternalPanelDoNotUseOrYouWillBeFired type={'success'}>
      A good news!
    </Modal._InternalPanelDoNotUseOrYouWillBeFired>
  );
};

const componentDemo: ComponentDemo = {
  demo: <Demo />,
  tokens: ['colorSuccess'],
  key: 'success',
};
export default componentDemo;
