// site/src/components/antdv-token-previewer/component-demos/modal/success.tsx
import { Modal } from 'ant-design-vue';

import type { ComponentDemo } from '../../interface';

const Demo = () => {
  return (
    <Modal._InternalPanelDoNotUseOrYouWillBeFired type={'success'}>
      A good news!
    </Modal._InternalPanelDoNotUseOrYouWillBeFired>
  );
};

const componentDemo: ComponentDemo = {
  demo: <Demo />,
  tokens: ['colorSuccess'],
  key: 'success',
};
export default componentDemo;

// site/src/components/antdv-token-previewer/component-demos/typography/success.tsx
import { defineComponent } from 'vue';
import { Typography } from 'ant-design-vue';
import type { ComponentDemo } from '../../interface';

const { Title, Text } = Typography;

const Demo = defineComponent({
  setup() {
    return () => (
      <div>
        <Title type={'success'} level={4}>
          Success Title
        </Title>
        <Text type={'success'}>success Text</Text>
      </div>
    );
  },
});

const componentDemo: ComponentDemo = {
  demo: <Demo />,
  tokens: ['colorSuccess'],
  key: 'success',
};

export default componentDemo;
