// site/src/components/antdv-token-previewer/component-demos/badge/success.tsx
import { defineComponent } from 'vue';
import { Badge, Space } from 'ant-design-vue';
import type { ComponentDemo } from '../../interface';

const Demo = defineComponent({
  setup() {
    return () => (
      <Space size="small">
        <Badge dot status={'success'} />
        Success
      </Space>
    );
  },
});

const componentDemo: ComponentDemo = {
  demo: <Demo />,
  tokens: ['colorSuccess'],
  key: 'success',
};

export default componentDemo;

// site/src/components/antdv-token-previewer/component-demos/progress/success.tsx
import { Progress, Space } from 'ant-design-vue';

import type { ComponentDemo } from '../../interface';

const Demo = () => (
  <Space direction={'vertical'} size={'large'}>
    <Space size={'large'}>
      <Progress percent={70} status="success" type={'dashboard'} />
      <Progress percent={80} status="success" type={'circle'} />
    </Space>
    <Progress percent={50} status="success" />
  </Space>
);

const componentDemo: ComponentDemo = {
  demo: <Demo />,
  tokens: ['colorSuccess'],
  key: 'success',
};

export default componentDemo;
