// components/vc-mentions/src/DropdownMenu.jsx
import Menu, { MenuItem } from '../../vc-menu';
import PropTypes from '../../_util/vue-types';
import { OptionProps } from './Option';

function noop() {}
export default {
  name: 'DropdownMenu',
  props: {
    prefixCls: PropTypes.string,
    options: PropTypes.arrayOf(OptionProps),
  },
  inject: {
    mentionsContext: { default: {} },
  },

  render() {
    const {
      notFoundContent,
      activeIndex,
      setActiveIndex,
      selectOption,
      onFocus = noop,
      onBlur = noop,
    } = this.mentionsContext;
    const { prefixCls, options } = this.$props;
    const activeOption = options[activeIndex] || {};

    return (
      <Menu
        {...{
          props: {
            prefixCls: `${prefixCls}-menu`,
            activeKey: activeOption.value,
          },
          on: {
            select: ({ key }) => {
              const option = options.find(({ value }) => value === key);
              selectOption(option);
            },
            focus: onFocus,
            blur: onBlur,
          },
        }}
      >
        {options.map((option, index) => {
          const { value, disabled, children } = option;
          return (
            <MenuItem
              key={value}
              disabled={disabled}
              onMouseenter={() => {
                setActiveIndex(index);
              }}
            >
              {children}
            </MenuItem>
          );
        })}
        {!options.length && <MenuItem disabled>{notFoundContent}</MenuItem>}
      </Menu>
    );
  },
};

// components/vc-mentions/src/DropdownMenu.tsx
import Menu, { Item as MenuItem } from '../../menu';
import PropTypes from '../../_util/vue-types';
import { defineComponent, inject } from 'vue';

function noop() {}

export default defineComponent({
  name: 'DropdownMenu',
  props: {
    prefixCls: PropTypes.string,
    options: PropTypes.any,
  },
  setup(props) {
    return () => {
      const {
        notFoundContent,
        activeIndex,
        setActiveIndex,
        selectOption,
        onFocus = noop,
        onBlur = noop,
      } = inject('mentionsContext');

      const { prefixCls, options } = props;
      const activeOption = options[activeIndex.value] || {};

      return (
        <Menu
          prefixCls={`${prefixCls}-menu`}
          activeKey={activeOption.value}
          onSelect={({ key }) => {
            const option = options.find(({ value }) => value === key);
            selectOption(option);
          }}
          onBlur={onBlur}
          onFocus={onFocus}
        >
          {[
            ...options.map((option, index) => {
              const { value, disabled, children } = option;
              return (
                <MenuItem
                  key={value}
                  disabled={disabled}
                  onMouseenter={() => {
                    setActiveIndex(index);
                  }}
                >
                  {children}
                </MenuItem>
              );
            }),
            !options.length && (
              <MenuItem key="notFoundContent" disabled>
                {notFoundContent.value}
              </MenuItem>
            ),
          ].filter(Boolean)}
        </Menu>
      );
    };
  },
});
