// components/menu/src/MenuItemGroup.jsx
import React from 'react'
import PropTypes from 'prop-types'
import createReactClass from 'create-react-class'

const MenuItemGroup = createReactClass({
  displayName: 'MenuItemGroup',

  propTypes: {
    renderMenuItem: PropTypes.func,
    index: PropTypes.number,
    className: PropTypes.string,
    rootPrefixCls: PropTypes.string,
  },

  getDefaultProps () {
    // To fix keyboard UX.
    return { disabled: true }
  },

  renderInnerMenuItem (item, subIndex) {
    const { renderMenuItem, index } = this.props
    return renderMenuItem(item, index, subIndex)
  },

  render () {
    const props = this.props
    const { className = '', rootPrefixCls } = props
    const titleClassName = `${rootPrefixCls}-item-group-title`
    const listClassName = `${rootPrefixCls}-item-group-list`
    return (
      <li className={`${className} ${rootPrefixCls}-item-group`}>
        <div
          className={titleClassName}
          title={typeof props.title === 'string' ? props.title : undefined}
        >
          {props.title}
        </div>
        <ul className={listClassName}>
          {React.Children.map(props.children, this.renderInnerMenuItem)}
        </ul>
      </li>
    )
  },
})

MenuItemGroup.isMenuItemGroup = true

export default MenuItemGroup

// components/vc-menu/MenuItemGroup.jsx
import PropTypes from '../_util/vue-types';
import { getComponent, getSlot } from '../_util/props-util';
import { menuAllProps } from './util';
import { defineComponent, inject } from 'vue';
import classNames from '../_util/classNames';
const injectExtraPropsKey = 'ANT_MENU_PROVIDER_PROPS_KEY';
const MenuItemGroup = {
  name: 'MenuItemGroup',
  inheritAttrs: false,
  setup() {
    return {
      injectExtraProps: inject(injectExtraPropsKey, () => ({})),
    };
  },
  props: {
    renderMenuItem: PropTypes.func,
    index: PropTypes.number,
    className: PropTypes.string,
    subMenuKey: PropTypes.string,
    rootPrefixCls: PropTypes.string,
    disabled: PropTypes.looseBool.def(true),
    title: PropTypes.any,
  },
  isMenuItemGroup: true,
  methods: {
    renderInnerMenuItem(item) {
      const { renderMenuItem, index, subMenuKey } = { ...this.$props, ...this.injectExtraProps };
      return renderMenuItem(item, index, subMenuKey);
    },
  },
  render() {
    const props = { ...this.$props, ...this.injectExtraProps, ...this.$attrs };
    const { class: cls = '', rootPrefixCls, title } = props;
    const titleClassName = `${rootPrefixCls}-item-group-title`;
    const listClassName = `${rootPrefixCls}-item-group-list`;
    menuAllProps.forEach(key => delete props[key]);
    // Set onClick to null, to ignore propagated onClick event
    delete props.onClick;
    const children = getSlot(this);
    return (
      <li {...props} class={classNames(cls, `${rootPrefixCls}-item-group`)}>
        <div class={titleClassName} title={typeof title === 'string' ? title : undefined}>
          {getComponent(this, 'title')}
        </div>
        <ul class={listClassName}>{children && children.map(this.renderInnerMenuItem)}</ul>
      </li>
    );
  },
};

export default defineComponent(MenuItemGroup);
